### ISSUE TITLE
Problem with VoiceIt.createEnrollment

### ISSUE THREAD

**Issue by tokbes** [voiceittech/voiceit-nodejs#1]
I'm trying to create enrollment by
```javascript
myVoiceIt.createEnrollment({
	email: user_email,
	password: user_password,
	pathToEnrollmentWav: '/home/users/username/voicePrint.wav',
	contentLanguage: 'en-US',
	callback: function(response){
	console.log("The Response Was ",response);
	}
});
```

but getting in response just plane html

```html
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta property="og:url" content="https://siv.voiceprintportal.com">
<meta property="og:image" content="https://siv.voiceprintportal.com/images/VoiceIt-Facebook.png">
<meta property="og:description"
	content="VoiceIt Technologies provides a cloud based, pay as you go, voice biometrics platform that enables developers and businesses to rapidly build and deploy voice biometric security solutions that meet their specific cyber security needs. Whether integrating into new or existing interactive voice response (IVR) systems, mobile applications, and/or web sites, VoiceIt removes the traditional obstacles of entry, it is easy to use, and provides a security platform at a reasonable cost.">
<meta property="og:title" content="VoiceIt Technologies LLC.">
<meta property="og:type" content="website">
<meta name="description"
	content="VoiceIt Technologies provides a cloud based, pay as you go, voice biometrics platform that enables developers and businesses to rapidly build and deploy voice biometric security solutions that meet their specific cyber security needs. Whether integrating into new or existing interactive voice response (IVR) systems, mobile applications, and/or web sites, VoiceIt removes the traditional obstacles of entry, it is easy to use, and provides a security platform at a reasonable cost.">
<meta name="keywords" content="security,biometrics,api,sdk,biometric,voice,security layer,two-factor,cloud-based,voiceit,VoiceIt,authentication,key,identification">
<meta name="author" content="VoiceIt">
....
```

**Comment by armaanbindra** [comment]
Hi tokbes, I was wondering whether you could help me recreate your condition, because I am trying the same API call using the node wrapper and it seems to be working well giving me an appropriate response like:

The Response Was  {"Result":"Success","EnrollmentID":"123456"","DetectedVoiceprintText":"Never forget tomorrow is a new day","DetectedTextConfidence":"100.0","ResponseCode":"SUC"}

I just have a few questions for you, that might help me resolve the issue:
Are you passing a full path to the wav file?

Could you provide the value for the user_email and user_password(you can change this to a different value in the VoiceIt console after we resolve the issue) variables you are using, also you can email these values to me with reference to this issue if you like, at armaan.bindra@voiceit-tech.com

Thank you,
Armaan
Software Developer at VoiceIt

**Comment by noelgrover** [comment]
Hello Tokbes,

We fixed the incorrectly formatted recordings passed with enrollment and authentication calls so that the JSON response is not correctly generated.

Please see min requirements at:  https://siv.voiceprintportal.com/apidocs.jsp

Thanks for reporting the bug and please let us know if you need any other help.

Sincerely,
Noel Grover
CEO
VoiceIt

**Comment by tokbes** [comment]
Thank you for fast response.
