### ISSUE TITLE
 message: 'Failed to add enrollment for userId : *********, low text confidence',

### ISSUE THREAD

**Issue by sarthakmis** [voiceittech/voiceit-nodejs#2]
Getting this error every time I run the server. Hope for the quick response

I am running this code

`myVoiceIt.createVoiceEnrollmentByUrl({
    userId:'usr_*********************',
    contentLanguage:"en-US",
    audioFileURL:"https://s3-us-west-2.amazonaws.com/******/*****.mp3"
},(jsonResponse)=>{
   console.log("Message Recieved:",jsonResponse)
});`

**Comment by armaanbindra** [comment]
Hi @sarthakmis, your code sample actually corresponds to our new Node JS wrapper for VoiceIt API 2.0 that is not related to this repository. It is at https://github.com/voiceittech/voiceit2-nodejs. Also your issue seems to be unrelated to the Node JS wrapper and seems to be simply be a issue where you are trying to send an audio file with a phrase that does not exist for your developer account. To use VoiceIt you need to to be able to use the same pre - approved phrase for enrollment three times and then for verification, which you can read more about at here https://blog.voiceit.io/voiceprint-phrases-fdf5c6b8e3c7. Please email us directly at support@voiceit.io for issues related to the API and developer account( we would be happy to help you there) and refrain from opening Github issues that are not directly related to the specific wrapper / sdk.
